using Newtonsoft.Json;
using System.Collections.Generic;

namespace KnowledgebaseSync.Models
{
    /// <summary>
    ///     An instance of CreateKbInputDTO for add operation.
    /// </summary>
    public class Add
    {
        /// <summary>
        ///     List of files to be added to knowledgebase.
        /// </summary>
        [JsonProperty("files")]
        public List<FileDTO> Files { get; set; }

        /// <summary>
        ///     List of QNA to be added to the index. Ids are generated by the service and should be omitted.
        /// </summary>
        [JsonProperty("qnaList")]
        public List<QnADTO> QnaList { get; set; }

        /// <summary>
        ///     List of URLs to be added to knowledgebase.
        /// </summary>
        [JsonProperty("urls")]
        public List<string> Urls { get; set; }
    }
}
